"""v1.2 ref book field

Revision ID: 05ae5bcdc5b4
Revises: 94a71e9e3941
Create Date: 2026-02-22 09:43:29.069985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ae5bcdc5b4'
down_revision: Union[str, Sequence[str], None] = '94a71e9e3941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.String(length=200), nullable=False))
    op.drop_column('books', 'descriptoin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('descriptoin', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
