"""v1.6 add compute field

Revision ID: 1d5d5f7bcda2
Revises: 5f05114d7e67
Create Date: 2026-03-24 12:13:59.335836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5d5f7bcda2'
down_revision: Union[str, Sequence[str], None] = '5f05114d7e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('code', sa.String(length=250), sa.Computed("CAST(id AS VARCHAR) || '-' || title", ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'code')
    # ### end Alembic commands ###
