"""v1_4_add_extra_field

Revision ID: 5f05114d7e67
Revises: a64ec4adae6e
Create Date: 2026-03-21 21:36:38.759971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f05114d7e67'
down_revision: Union[str, Sequence[str], None] = 'a64ec4adae6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'extra_data')
    # ### end Alembic commands ###
