"""v1.1 add book field

Revision ID: 94a71e9e3941
Revises: 98113cc14c41
Create Date: 2026-02-22 09:04:34.632290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a71e9e3941'
down_revision: Union[str, Sequence[str], None] = '98113cc14c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('descriptoin', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'descriptoin')
    # ### end Alembic commands ###
